#!/usr/bin/env bash
# vCenter Prometheus Exporter - install to system directory (run as root)
set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
INSTALL_PREFIX="${INSTALL_PREFIX:-/opt/vcenter-exporter}"

# --- usage ---
usage() {
  echo "Usage: sudo $0 [--prefix /path] [--upgrade] [--reconfigure]"
  echo "  Installs to ${INSTALL_PREFIX} by default. Service runs as root."
  echo "  --prefix DIR   Install to DIR (default: /opt/vcenter-exporter)"
  echo "  --upgrade      Copy updated files and refresh venv, then restart service"
  echo "  --reconfigure  Prompt for .env again and overwrite existing"
  exit 0
}

# --- require root ---
require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "This script must be run as root. Example: sudo $0"
    exit 1
  fi
}

# --- prompts ---
prompt_value() {
  local name="$1" default="$2" secret="${3:-}"
  local val
  if [[ -n "$default" ]]; then
    if [[ -n "$secret" ]]; then
      read -r -s -p "$name [$default]: " val
      echo >&2
    else
      read -r -p "$name [$default]: " val
    fi
    echo "${val:-$default}"
  else
    if [[ -n "$secret" ]]; then
      read -r -s -p "$name: " val
      echo >&2
    else
      read -r -p "$name: " val
    fi
    echo "$val"
  fi
}

prompt_yes_no() {
  local prompt="$1" default="${2:-y}"
  local val
  read -r -p "$prompt [Y/n]: " val
  val="${val:-$default}"
  [[ "$val" =~ ^[yY] ]] || [[ "$val" =~ ^[yY][eE][sS] ]]
}

# --- copy repo to prefix (exclude .git, .venv, __pycache__, .env) ---
copy_to_prefix() {
  echo "Copying files to $INSTALL_PREFIX ..."
  mkdir -p "$INSTALL_PREFIX"
  if command -v rsync &>/dev/null; then
    rsync -a \
      --exclude='.git' \
      --exclude='.venv' \
      --exclude='__pycache__' \
      --exclude='.env' \
      --exclude='*.pyc' \
      "$REPO_ROOT/" "$INSTALL_PREFIX/"
  else
    (cd "$REPO_ROOT" && tar --exclude='.git' --exclude='.venv' --exclude='.env' --exclude='__pycache__' --exclude='*.pyc' -cf - .) \
      | (cd "$INSTALL_PREFIX" && tar -xf -)
  fi
  echo "Files copied."
}

# --- create venv and install deps in prefix ---
setup_venv() {
  local do_upgrade="${1:-}"
  if [[ ! -d "$INSTALL_PREFIX/.venv" ]]; then
    echo "Creating virtual environment in $INSTALL_PREFIX/.venv ..."
    python3 -m venv "$INSTALL_PREFIX/.venv"
  fi
  echo "Installing dependencies in $INSTALL_PREFIX/.venv ..."
  "$INSTALL_PREFIX/.venv/bin/python" -m pip install -q --upgrade pip
  if [[ -n "$do_upgrade" ]]; then
    "$INSTALL_PREFIX/.venv/bin/python" -m pip install -q --upgrade -r "$INSTALL_PREFIX/requirements.txt"
    "$INSTALL_PREFIX/.venv/bin/python" -m pip install -q --upgrade -e "$INSTALL_PREFIX"
  else
    "$INSTALL_PREFIX/.venv/bin/python" -m pip install -q -r "$INSTALL_PREFIX/requirements.txt"
    "$INSTALL_PREFIX/.venv/bin/python" -m pip install -q -e "$INSTALL_PREFIX"
  fi
  if ! "$INSTALL_PREFIX/.venv/bin/python" -c "from vmware.vapi.vsphere.client import create_vsphere_client" 2>/dev/null; then
    echo "ERROR: VCF SDK (vmware-vcenter) could not be imported."
    return 1
  fi
  if "$INSTALL_PREFIX/.venv/bin/python" -c "import pyVmomi" 2>/dev/null; then
    echo "Python environment ready (VCF SDK + pyvmomi)."
  else
    echo "Python environment ready (VCF SDK). Install pyvmomi for performance fallback: $INSTALL_PREFIX/.venv/bin/pip install pyvmomi"
  fi
}

# --- gather config and write .env to prefix ---
gather_and_write_env() {
  echo ""
  echo "vCenter Prometheus Exporter - configuration"
  echo "Leave default in brackets empty to use the default."
  echo ""

  local server user pass verify_ssl host port
  server=$(prompt_value "vCenter URL (e.g. https://vcenter.example.com)" "")
  while [[ -z "$server" ]]; do
    echo "vCenter URL is required."
    server=$(prompt_value "vCenter URL (e.g. https://vcenter.example.com)" "")
  done
  if [[ "$server" != https://* && "$server" != http://* ]]; then
    server="https://$server"
  fi

  user=$(prompt_value "vCenter user" "administrator@vsphere.local")
  pass=$(prompt_value "vCenter password" "" "secret")
  while [[ -z "$pass" ]]; do
    echo "Password is required."
    pass=$(prompt_value "vCenter password" "" "secret")
  done

  if prompt_yes_no "Verify vCenter SSL certificate?" "y"; then
    verify_ssl="true"
  else
    verify_ssl="false"
  fi

  host=$(prompt_value "Exporter listen address" "0.0.0.0")
  port=$(prompt_value "Exporter port" "9680")
  port="${port:-9680}"

  cat > "$INSTALL_PREFIX/.env" << EOF
# Generated by install.sh
VCENTER_SERVER=$server
VCENTER_USER=$user
VCENTER_PASSWORD=$pass
VCENTER_VERIFY_SSL=$verify_ssl
EXPORTER_HOST=$host
EXPORTER_PORT=$port
SCRAPE_INTERVAL=300
EOF
  chmod 600 "$INSTALL_PREFIX/.env"
  echo ""
  echo "Wrote $INSTALL_PREFIX/.env"
}

# --- install systemd unit (service runs as root) ---
install_systemd() {
  if [[ ! -f "$INSTALL_PREFIX/.env" ]]; then
    echo "Missing $INSTALL_PREFIX/.env. Run config step first."
    return 1
  fi
  if [[ ! -x "$INSTALL_PREFIX/.venv/bin/python" ]]; then
    echo "Missing $INSTALL_PREFIX/.venv/bin/python. Run install first."
    return 1
  fi
  if ! "$INSTALL_PREFIX/.venv/bin/python" -c "from vmware.vapi.vsphere.client import create_vsphere_client" 2>/dev/null; then
    echo "VCF SDK not found in $INSTALL_PREFIX/.venv. Run: sudo $0 --upgrade"
    return 1
  fi

  UNIT_FILE="/etc/systemd/system/vcenter-exporter.service"
  cat > "$UNIT_FILE" << EOF
[Unit]
Description=vCenter Prometheus Exporter
Documentation=https://github.com/tysonhammen/VCFGrafana
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_PREFIX
EnvironmentFile=$INSTALL_PREFIX/.env
ExecStart=$INSTALL_PREFIX/.venv/bin/python -m vcenter_exporter.main
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  echo "Created $UNIT_FILE"
  systemctl daemon-reload
  systemctl enable vcenter-exporter.service
  systemctl start vcenter-exporter.service
  echo ""
  echo "Service 'vcenter-exporter' is enabled and started (running as root)."
  echo "  status: systemctl status vcenter-exporter"
  echo "  logs:   journalctl -u vcenter-exporter -f"
  echo "  stop:   systemctl stop vcenter-exporter"
}

# --- parse args ---
RECONFIGURE=""
DO_UPGRADE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      INSTALL_PREFIX="${2:?Missing argument to --prefix}"
      shift 2
      ;;
    --upgrade)
      DO_UPGRADE=1
      shift
      ;;
    --reconfigure)
      RECONFIGURE=1
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1"
      usage
      ;;
  esac
done

# --- main ---
require_root

if [[ -n "$DO_UPGRADE" ]]; then
  if [[ ! -d "$INSTALL_PREFIX" ]]; then
    echo "No existing install at $INSTALL_PREFIX. Run full install: sudo $0"
    exit 1
  fi
  copy_to_prefix
  setup_venv "upgrade"
  systemctl restart vcenter-exporter.service 2>/dev/null && echo "Service restarted." || true
  echo ""
  echo "Upgrade complete. Restart if needed: systemctl restart vcenter-exporter"
  exit 0
fi

# Reconfigure only (no copy, no venv)
if [[ -n "$RECONFIGURE" ]] && [[ -d "$INSTALL_PREFIX" ]] && [[ -f "$INSTALL_PREFIX/.venv/bin/python" ]]; then
  gather_and_write_env
  systemctl restart vcenter-exporter.service 2>/dev/null && echo "Service restarted." || true
  echo "Reconfigured $INSTALL_PREFIX/.env"
  exit 0
fi

# Full install
copy_to_prefix
setup_venv "" || exit 1

if [[ ! -f "$INSTALL_PREFIX/.env" ]] || [[ -n "$RECONFIGURE" ]]; then
  gather_and_write_env
else
  echo "Existing $INSTALL_PREFIX/.env found. Use --reconfigure to overwrite."
fi

install_systemd || exit 1

echo ""
echo "Installation complete. Exporter is installed at $INSTALL_PREFIX and running as a service."
