#!/usr/bin/env bash
# vCenter Prometheus Exporter - interactive install and systemd setup
set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
cd "$REPO_ROOT"

# --- prompts (no-op when --install-systemd) ---
prompt_value() {
  local name="$1" default="$2" secret="${3:-}"
  local var val
  if [[ -n "$default" ]]; then
    if [[ -n "$secret" ]]; then
      read -r -s -p "$name [$default]: " val
      echo >&2
    else
      read -r -p "$name [$default]: " val
    fi
    echo "${val:-$default}"
  else
    if [[ -n "$secret" ]]; then
      read -r -s -p "$name: " val
      echo >&2
    else
      read -r -p "$name: " val
    fi
    echo "$val"
  fi
}

prompt_yes_no() {
  local prompt="$1" default="${2:-y}"
  local val
  read -r -p "$prompt [Y/n]: " val
  val="${val:-$default}"
  [[ "$val" =~ ^[yY] ]] || [[ "$val" =~ ^[yY][eE][sS] ]]
}

gather_and_write_env() {
  echo ""
  echo "vCenter Prometheus Exporter - configuration"
  echo "Leave default in brackets empty to use the default."
  echo ""

  local server user pass verify_ssl host port
  server=$(prompt_value "vCenter URL (e.g. https://vcenter.example.com)" "")
  while [[ -z "$server" ]]; do
    echo "vCenter URL is required."
    server=$(prompt_value "vCenter URL (e.g. https://vcenter.example.com)" "")
  done
  if [[ "$server" != https://* && "$server" != http://* ]]; then
    server="https://$server"
  fi

  user=$(prompt_value "vCenter user" "administrator@vsphere.local")
  pass=$(prompt_value "vCenter password" "" "secret")
  while [[ -z "$pass" ]]; do
    echo "Password is required."
    pass=$(prompt_value "vCenter password" "" "secret")
  done

  if prompt_yes_no "Verify vCenter SSL certificate?" "y"; then
    verify_ssl="true"
  else
    verify_ssl="false"
  fi

  host=$(prompt_value "Exporter listen address" "0.0.0.0")
  port=$(prompt_value "Exporter port" "9680")
  port="${port:-9680}"

  cat > "$REPO_ROOT/.env" << EOF
# Generated by install.sh
VCENTER_SERVER=$server
VCENTER_USER=$user
VCENTER_PASSWORD=$pass
VCENTER_VERIFY_SSL=$verify_ssl
EXPORTER_HOST=$host
EXPORTER_PORT=$port
SCRAPE_INTERVAL=300
EOF
  chmod 600 "$REPO_ROOT/.env"
  echo ""
  echo "Wrote $REPO_ROOT/.env"
}

ensure_venv() {
  if [[ ! -d "$REPO_ROOT/.venv" ]]; then
    echo "Creating virtual environment in $REPO_ROOT/.venv ..."
    python3 -m venv "$REPO_ROOT/.venv"
  fi
  echo "Installing/upgrading package in .venv ..."
  "$REPO_ROOT/.venv/bin/python" -m pip install -q --upgrade pip
  "$REPO_ROOT/.venv/bin/python" -m pip install -q -r "$REPO_ROOT/requirements.txt"
  "$REPO_ROOT/.venv/bin/python" -m pip install -q -e "$REPO_ROOT"
  if ! "$REPO_ROOT/.venv/bin/python" -c "from vmware.vapi.vsphere.client import create_vsphere_client" 2>/dev/null; then
    echo "ERROR: VCF SDK (vmware-vcenter) could not be imported. Install with: $REPO_ROOT/.venv/bin/pip install -r requirements.txt"
    return 1
  fi
  echo "Python environment ready (VCF SDK available)."
}

# Clean old bytecode and ensure VCF SDK is installed. Use after git pull / upgrade.
upgrade_venv() {
  echo "Upgrading vCenter exporter: cleaning old implementations and ensuring VCF SDK ..."
  # Remove stale bytecode from any previous implementation (exclude .venv)
  while IFS= read -r -d '' d; do
    rm -rf "$d"
  done < <(find "$REPO_ROOT" -type d -name "__pycache__" ! -path "$REPO_ROOT/.venv/*" -print0 2>/dev/null)
  find "$REPO_ROOT" -type f -name "*.pyc" ! -path "$REPO_ROOT/.venv/*" -delete 2>/dev/null || true
  if [[ ! -d "$REPO_ROOT/.venv" ]]; then
    echo "No .venv found. Running full install."
    ensure_venv
    return $?
  fi
  "$REPO_ROOT/.venv/bin/python" -m pip install -q --upgrade pip
  "$REPO_ROOT/.venv/bin/python" -m pip install -q --upgrade -r "$REPO_ROOT/requirements.txt"
  "$REPO_ROOT/.venv/bin/python" -m pip install -q -e "$REPO_ROOT"
  if ! "$REPO_ROOT/.venv/bin/python" -c "from vmware.vapi.vsphere.client import create_vsphere_client" 2>/dev/null; then
    echo "ERROR: VCF SDK (vmware-vcenter) is not available after upgrade. Run: $REPO_ROOT/.venv/bin/pip install -r $REPO_ROOT/requirements.txt"
    return 1
  fi
  echo "Upgrade complete. VCF SDK is available."
}

install_systemd() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "Systemd install must be run as root. Run: sudo $0 --install-systemd"
    return 1
  fi
  # Run as the user that owns the repo (e.g. idadm)
  REPO_OWNER="$(stat -c %U "$REPO_ROOT" 2>/dev/null)" || REPO_OWNER="root"
  if [[ ! -f "$REPO_ROOT/.env" ]]; then
    echo "Missing $REPO_ROOT/.env. Run ./install.sh first (without --install-systemd)."
    return 1
  fi
  if [[ ! -x "$REPO_ROOT/.venv/bin/python" ]]; then
    echo "Missing $REPO_ROOT/.venv/bin/python. Run ./install.sh first."
    return 1
  fi
  if ! "$REPO_ROOT/.venv/bin/python" -c "from vmware.vapi.vsphere.client import create_vsphere_client" 2>/dev/null; then
    echo "VCF SDK (vmware-vcenter) not found in .venv. Run: ./install.sh --upgrade"
    return 1
  fi

  UNIT_FILE="/etc/systemd/system/vcenter-exporter.service"
  cat > "$UNIT_FILE" << EOF
[Unit]
Description=vCenter Prometheus Exporter
Documentation=https://github.com/tysonhammen/VCFGrafana
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$REPO_OWNER
WorkingDirectory=$REPO_ROOT
EnvironmentFile=$REPO_ROOT/.env
ExecStart=$REPO_ROOT/.venv/bin/python -m vcenter_exporter.main
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  echo "Created $UNIT_FILE"
  systemctl daemon-reload
  systemctl enable vcenter-exporter.service
  systemctl start vcenter-exporter.service
  echo ""
  echo "Service 'vcenter-exporter' is enabled and started."
  echo "  status: systemctl status vcenter-exporter"
  echo "  logs:   journalctl -u vcenter-exporter -f"
  echo "  stop:   systemctl stop vcenter-exporter"
}

# --- main ---
if [[ "${1:-}" == "--install-systemd" ]]; then
  install_systemd
  exit 0
fi

if [[ "${1:-}" == "--upgrade" ]]; then
  upgrade_venv || exit 1
  echo ""
  echo "To restart the exporter if running as a service: sudo systemctl restart vcenter-exporter"
  exit 0
fi

# Interactive install
if [[ ! -f "$REPO_ROOT/.env" ]]; then
  gather_and_write_env
else
  echo "Existing .env found. Overwrite? (current file will be replaced)"
  if prompt_yes_no "Overwrite .env?" "n"; then
    gather_and_write_env
  fi
fi

ensure_venv

echo ""
echo "Installation complete. You can run the exporter now:"
echo "  $REPO_ROOT/.venv/bin/python -m vcenter_exporter.main"
echo "  or: $REPO_ROOT/.venv/bin/vcenter-exporter"
echo ""
if [[ -d /run/systemd/system ]] && command -v systemctl &>/dev/null; then
  if prompt_yes_no "Install and enable systemd service (start on boot, restart on failure)?" "y"; then
    SCRIPT_PATH="$REPO_ROOT/$(basename "${BASH_SOURCE[0]:-$0}")"
    sudo "$SCRIPT_PATH" --install-systemd
  else
    echo "Skipped. To install the service later, run: sudo $0 --install-systemd"
  fi
  echo ""
fi
